export interface Booking {
    id: string
    guestName: string
    guestEmail: string
    guestPhone: string
    propertyId: string
    propertyName: string
    neighborhood: string
    checkIn: Date
    checkOut: Date
    nights: number
    totalAmount: number
    status: 'pending' | 'confirmed' | 'checked-in' | 'completed' | 'cancelled'
    paymentStatus: 'paid' | 'pending' | 'refunded'
    createdAt: Date
    guests: number
}

export interface AdminProperty {
    id: string
    slug: string
    name: string
    neighborhood: string
    bedrooms: number
    bathrooms: number
    guestCapacity: number
    pricePerNight: number
    status: 'live' | 'draft' | 'maintenance'
    image: string
    occupancyRate: number
    totalBookings: number
    totalRevenue: number
}

export const adminProperties: AdminProperty[] = [
    {
        id: 'prop-sundry-house',
        slug: 'sundry-house',
        name: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        bedrooms: 2,
        bathrooms: 2,
        guestCapacity: 4,
        pricePerNight: 95000,
        status: 'live',
        image: 'sundry-house-01.webp',
        occupancyRate: 78,
        totalBookings: 24,
        totalRevenue: 8540000,
    },
    {
        id: 'prop-eko-brief',
        slug: 'the-eko-brief',
        name: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        bedrooms: 3,
        bathrooms: 3,
        guestCapacity: 6,
        pricePerNight: 180000,
        status: 'live',
        image: 'eko-brief-01.jpeg',
        occupancyRate: 85,
        totalBookings: 18,
        totalRevenue: 12960000,
    },
    {
        id: 'prop-marina-loft',
        slug: 'marina-loft',
        name: 'Marina Loft',
        neighborhood: 'Victoria Island',
        bedrooms: 1,
        bathrooms: 1,
        guestCapacity: 2,
        pricePerNight: 125000,
        status: 'live',
        image: 'marina-loft-01.jpeg',
        occupancyRate: 62,
        totalBookings: 14,
        totalRevenue: 6250000,
    },
    {
        id: 'prop-palm-and-pine',
        slug: 'palm-and-pine',
        name: 'Palm & Pine',
        neighborhood: 'Banana Island',
        bedrooms: 3,
        bathrooms: 3,
        guestCapacity: 6,
        pricePerNight: 240000,
        status: 'live',
        image: 'palm-and-pine-01.jpeg',
        occupancyRate: 91,
        totalBookings: 22,
        totalRevenue: 21120000,
    },
    {
        id: 'prop-six-degrees',
        slug: 'six-degrees',
        name: 'Six Degrees',
        neighborhood: 'Ikoyi',
        bedrooms: 1,
        bathrooms: 1,
        guestCapacity: 2,
        pricePerNight: 110000,
        status: 'maintenance',
        image: 'six-degrees-01.webp',
        occupancyRate: 0,
        totalBookings: 11,
        totalRevenue: 4830000,
    },
    {
        id: 'prop-dawn-house',
        slug: 'the-dawn-house',
        name: 'The Dawn House',
        neighborhood: 'Lekki Phase 2',
        bedrooms: 2,
        bathrooms: 2,
        guestCapacity: 3,
        pricePerNight: 78000,
        status: 'draft',
        image: 'dawn-house-01.jpeg',
        occupancyRate: 0,
        totalBookings: 0,
        totalRevenue: 0,
    },
]

export const adminBookings: Booking[] = [
    // ---- Completed (5) — check-out in the past ----
    {
        id: 'bkg-0001',
        guestName: 'Adaeze Okafor',
        guestEmail: 'adaeze.okafor@gmail.com',
        guestPhone: '+234 803 412 5566',
        propertyId: 'prop-sundry-house',
        propertyName: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        checkIn: new Date(2026, 2, 10),
        checkOut: new Date(2026, 2, 14),
        nights: 4,
        totalAmount: 380000,
        status: 'completed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 1, 22),
        guests: 2,
    },
    {
        id: 'bkg-0002',
        guestName: 'Tobi Adeyemi',
        guestEmail: 'tobi.adeyemi@gmail.com',
        guestPhone: '+234 805 778 2231',
        propertyId: 'prop-marina-loft',
        propertyName: 'Marina Loft',
        neighborhood: 'Victoria Island',
        checkIn: new Date(2026, 3, 1),
        checkOut: new Date(2026, 3, 5),
        nights: 4,
        totalAmount: 500000,
        status: 'completed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 2, 15),
        guests: 2,
    },
    {
        id: 'bkg-0003',
        guestName: 'Funmi Bello',
        guestEmail: 'funmi.bello@outlook.com',
        guestPhone: '+234 706 991 4480',
        propertyId: 'prop-six-degrees',
        propertyName: 'Six Degrees',
        neighborhood: 'Ikoyi',
        checkIn: new Date(2026, 1, 25),
        checkOut: new Date(2026, 2, 1),
        nights: 4,
        totalAmount: 440000,
        status: 'completed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 1, 10),
        guests: 1,
    },
    {
        id: 'bkg-0004',
        guestName: 'Emeka Okonkwo',
        guestEmail: 'emeka.okonkwo@gmail.com',
        guestPhone: '+234 802 365 7711',
        propertyId: 'prop-palm-and-pine',
        propertyName: 'Palm & Pine',
        neighborhood: 'Banana Island',
        checkIn: new Date(2026, 3, 15),
        checkOut: new Date(2026, 3, 18),
        nights: 3,
        totalAmount: 720000,
        status: 'completed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 2, 25),
        guests: 4,
    },
    {
        id: 'bkg-0005',
        guestName: 'Chiamaka Nwankwo',
        guestEmail: 'chiamaka.nwankwo@gmail.com',
        guestPhone: '+234 809 224 6678',
        propertyId: 'prop-eko-brief',
        propertyName: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        checkIn: new Date(2026, 3, 25),
        checkOut: new Date(2026, 4, 1),
        nights: 6,
        totalAmount: 1080000,
        status: 'completed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 3, 5),
        guests: 5,
    },

    // ---- Checked-in (2) — check-in past, check-out future ----
    {
        id: 'bkg-0006',
        guestName: 'Ifeoma Oluwaseun',
        guestEmail: 'ifeoma.o@gmail.com',
        guestPhone: '+234 803 887 1102',
        propertyId: 'prop-sundry-house',
        propertyName: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        checkIn: new Date(2026, 4, 18),
        checkOut: new Date(2026, 4, 24),
        nights: 6,
        totalAmount: 570000,
        status: 'checked-in',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 1),
        guests: 3,
    },
    {
        id: 'bkg-0007',
        guestName: 'Kunle Adebayo',
        guestEmail: 'kunle.adebayo@yahoo.com',
        guestPhone: '+234 706 334 5582',
        propertyId: 'prop-marina-loft',
        propertyName: 'Marina Loft',
        neighborhood: 'Victoria Island',
        checkIn: new Date(2026, 4, 20),
        checkOut: new Date(2026, 4, 25),
        nights: 5,
        totalAmount: 625000,
        status: 'checked-in',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 5),
        guests: 2,
    },

    // ---- Confirmed (8) — check-in future, paid ----
    {
        id: 'bkg-0008',
        guestName: 'Yetunde Eze',
        guestEmail: 'yetunde.eze@gmail.com',
        guestPhone: '+234 805 442 9912',
        propertyId: 'prop-eko-brief',
        propertyName: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        checkIn: new Date(2026, 4, 28),
        checkOut: new Date(2026, 5, 1),
        nights: 4,
        totalAmount: 720000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 10),
        guests: 4,
    },
    {
        id: 'bkg-0009',
        guestName: 'Tunde Akpan',
        guestEmail: 'tunde.akpan@gmail.com',
        guestPhone: '+234 802 119 7733',
        propertyId: 'prop-palm-and-pine',
        propertyName: 'Palm & Pine',
        neighborhood: 'Banana Island',
        checkIn: new Date(2026, 5, 5),
        checkOut: new Date(2026, 5, 10),
        nights: 5,
        totalAmount: 1200000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 15),
        guests: 6,
    },
    {
        id: 'bkg-0010',
        guestName: 'Bukola Ojo',
        guestEmail: 'bukola.ojo@gmail.com',
        guestPhone: '+234 809 556 4421',
        propertyId: 'prop-sundry-house',
        propertyName: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        checkIn: new Date(2026, 5, 12),
        checkOut: new Date(2026, 5, 15),
        nights: 3,
        totalAmount: 285000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 18),
        guests: 2,
    },
    {
        id: 'bkg-0011',
        guestName: 'Chika Ibrahim',
        guestEmail: 'chika.ibrahim@gmail.com',
        guestPhone: '+234 803 992 1145',
        propertyId: 'prop-marina-loft',
        propertyName: 'Marina Loft',
        neighborhood: 'Victoria Island',
        checkIn: new Date(2026, 5, 18),
        checkOut: new Date(2026, 5, 22),
        nights: 4,
        totalAmount: 500000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 20),
        guests: 2,
    },
    {
        id: 'bkg-0012',
        guestName: 'Femi Williams',
        guestEmail: 'femi.williams@gmail.com',
        guestPhone: '+234 706 882 3320',
        propertyId: 'prop-eko-brief',
        propertyName: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        checkIn: new Date(2026, 5, 25),
        checkOut: new Date(2026, 5, 30),
        nights: 5,
        totalAmount: 900000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 21),
        guests: 5,
    },
    {
        id: 'bkg-0013',
        guestName: 'Aisha Lawal',
        guestEmail: 'aisha.lawal@gmail.com',
        guestPhone: '+234 805 217 4477',
        propertyId: 'prop-palm-and-pine',
        propertyName: 'Palm & Pine',
        neighborhood: 'Banana Island',
        checkIn: new Date(2026, 6, 1),
        checkOut: new Date(2026, 6, 7),
        nights: 6,
        totalAmount: 1440000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 12),
        guests: 6,
    },
    {
        id: 'bkg-0014',
        guestName: 'David Adeniyi',
        guestEmail: 'david.adeniyi@gmail.com',
        guestPhone: '+234 802 446 5567',
        propertyId: 'prop-sundry-house',
        propertyName: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        checkIn: new Date(2026, 6, 8),
        checkOut: new Date(2026, 6, 12),
        nights: 4,
        totalAmount: 380000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 19),
        guests: 3,
    },
    {
        id: 'bkg-0015',
        guestName: 'Jola Onyeka',
        guestEmail: 'jola.onyeka@gmail.com',
        guestPhone: '+234 809 117 8823',
        propertyId: 'prop-marina-loft',
        propertyName: 'Marina Loft',
        neighborhood: 'Victoria Island',
        checkIn: new Date(2026, 6, 14),
        checkOut: new Date(2026, 6, 17),
        nights: 3,
        totalAmount: 375000,
        status: 'confirmed',
        paymentStatus: 'paid',
        createdAt: new Date(2026, 4, 22),
        guests: 1,
    },

    // ---- Pending (5) — future, awaiting payment ----
    {
        id: 'bkg-0016',
        guestName: 'Wale Okafor',
        guestEmail: 'wale.okafor@gmail.com',
        guestPhone: '+234 803 559 2014',
        propertyId: 'prop-eko-brief',
        propertyName: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        checkIn: new Date(2026, 4, 30),
        checkOut: new Date(2026, 5, 3),
        nights: 4,
        totalAmount: 720000,
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: new Date(2026, 4, 21),
        guests: 4,
    },
    {
        id: 'bkg-0017',
        guestName: 'Ngozi Adeyemi',
        guestEmail: 'ngozi.adeyemi@gmail.com',
        guestPhone: '+234 706 224 8810',
        propertyId: 'prop-palm-and-pine',
        propertyName: 'Palm & Pine',
        neighborhood: 'Banana Island',
        checkIn: new Date(2026, 5, 15),
        checkOut: new Date(2026, 5, 20),
        nights: 5,
        totalAmount: 1200000,
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: new Date(2026, 4, 22),
        guests: 5,
    },
    {
        id: 'bkg-0018',
        guestName: 'Olamide Bello',
        guestEmail: 'olamide.bello@gmail.com',
        guestPhone: '+234 802 778 9921',
        propertyId: 'prop-sundry-house',
        propertyName: 'Sundry House',
        neighborhood: 'Lekki Phase 1',
        checkIn: new Date(2026, 6, 5),
        checkOut: new Date(2026, 6, 9),
        nights: 4,
        totalAmount: 380000,
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: new Date(2026, 4, 22),
        guests: 2,
    },
    {
        id: 'bkg-0019',
        guestName: 'Zainab Okonkwo',
        guestEmail: 'zainab.okonkwo@gmail.com',
        guestPhone: '+234 805 339 5544',
        propertyId: 'prop-marina-loft',
        propertyName: 'Marina Loft',
        neighborhood: 'Victoria Island',
        checkIn: new Date(2026, 6, 10),
        checkOut: new Date(2026, 6, 14),
        nights: 4,
        totalAmount: 500000,
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: new Date(2026, 4, 22),
        guests: 2,
    },
    {
        id: 'bkg-0020',
        guestName: 'Seun Nwankwo',
        guestEmail: 'seun.nwankwo@gmail.com',
        guestPhone: '+234 809 661 7732',
        propertyId: 'prop-eko-brief',
        propertyName: 'The Eko Brief',
        neighborhood: 'Eko Atlantic',
        checkIn: new Date(2026, 6, 18),
        checkOut: new Date(2026, 6, 21),
        nights: 3,
        totalAmount: 540000,
        status: 'pending',
        paymentStatus: 'pending',
        createdAt: new Date(2026, 4, 22),
        guests: 3,
    },

    // ---- Cancelled (1) ----
    {
        id: 'bkg-0021',
        guestName: 'Tobi Williams',
        guestEmail: 'tobi.williams@gmail.com',
        guestPhone: '+234 803 224 6655',
        propertyId: 'prop-palm-and-pine',
        propertyName: 'Palm & Pine',
        neighborhood: 'Banana Island',
        checkIn: new Date(2026, 5, 8),
        checkOut: new Date(2026, 5, 12),
        nights: 4,
        totalAmount: 960000,
        status: 'cancelled',
        paymentStatus: 'refunded',
        createdAt: new Date(2026, 4, 15),
        guests: 4,
    },
]
